import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Share_Tech_Mono } from "next/font/google";
const shareTechMono = Share_Tech_Mono({
  subsets: ["latin"],
  weight: "400", // Only weight 400 exists for Share Tech Mono
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={shareTechMono.className}>{children}</body>
    </html>
  );
}
